"""empty message

Revision ID: 58530e6ecf26
Revises: 
Create Date: 2023-05-24 13:28:13.764267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58530e6ecf26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
