"""empty message

Revision ID: d2449589bb73
Revises: 58530e6ecf26
Create Date: 2023-05-24 13:31:25.451865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2449589bb73'
down_revision = '58530e6ecf26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Enum('novel', 'psychology', 'english', 'computer', name='subjects'), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('stop_date', sa.Date(), nullable=True),
    sa.Column('end_status', sa.Boolean(), nullable=True),
    sa.Column('favorit_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestionbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('who', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.Enum('novel', 'psychology', 'english', 'computer', name='subjects'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestionbook_id'), 'suggestionbook', ['id'], unique=False)
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['readbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_id'), 'notebook', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_id'), table_name='notebook')
    op.drop_table('notebook')
    op.drop_index(op.f('ix_suggestionbook_id'), table_name='suggestionbook')
    op.drop_table('suggestionbook')
    op.drop_table('readbook')
    # ### end Alembic commands ###
